sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install tox tox-travis coverage coveralls

script:
  - coverage run --source=jeaves tox

after_success:
  - coveralls
