language: python
cache:
    pip: true

services:
    - postgresql
addons:
    # 9.4 supports JSONB fields, but 9.5 adds the ability to do
    # CREATE INDEX IF NOT EXISTS
    postgresql: "9.5"
before_script:
  - psql -c "CREATE DATABASE travisci;" -U postgres

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install tox tox-travis

script:
  - tox
